# ----------- CONFIGURABLE START -----------
title:            "Aprende TI"
description:      "Un blog para aprender sobre Tecnologías de la Información"
url:              https://educacion4ti.github.io/aprendiendoTI # Site url, without a slash at the end.
signoff:          "educacion4ti" # Your name
#facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
#google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Publicaciones
    url:          /
    external:     false
  - name:         Acerca de
    url:          /about
    external:     false
  - name:         Presentaciones
    url:          /presentaciones
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
